spring:
  application:
    name: bktapi-java-2
  profiles:
    active: sit

server:
  port: 8877
  servlet:
    context-path: /bktapi-java-2

mergepdf:
  cron: ${MERGEPDF_CRON_PARAMETER:0 59 23 * * ?}
  input-docker-volume-name: ${INPUT_DOCKER_VOLUME_NAME}
  output-docker-volume-name: ${OUTPUT_DOCKER_VOLUME_NAME}

---

spring:
  config:
    activate:
      on-profile: sit

  datasource:
    url: jdbc:sqlserver://10.1.0.92:1433;encrypt=true;trustServerCertificate=true;databaseName=BHAKTI
    username: mishirin
    password: br4v01nd14T4n990
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: none

---

spring:
  config:
    activate:
      on-profile: qc

  datasource:
    url: jdbc:sqlserver://${SQL_SERVER_IP}:1433;encrypt=true;trustServerCertificate=true;databaseName=${SQL_SERVER_DATABASE}
    username: mishirin
    password: br4v01nd14T4n990
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: none

---

spring:
  config:
    activate:
      on-profile: production

  datasource:
    url: jdbc:sqlserver://${SQL_SERVER_IP}:1433;encrypt=true;trustServerCertificate=true;databaseName=${SQL_SERVER_DATABASE}
    username: mishirin
    password: br4v01nd14T4n990
    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    show-sql: true
    hibernate:
      ddl-auto: none
